---
# Upgrade zen secure nodes

- name: upgrade zen secnodes
  hosts: zen-nodes
  remote_user: root

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Upgrading zen-node
      service:
        name: zen-node
        state: restarted
        enabled: yes

    - name: Upgrading zen-secnodetracker
      service:
        name: zen-secnodetracker
        state: restarted
        enabled: yes
